Яндекс: '1740'
Фабрика Решений: '4596113'
Carbon Soft: '1204987'
Группа Компаний РУСАГРО: '23186'
А-Телематика: '6019841'
ГК Фармасинтез: '829326'
Шлюмберже: '2791'
Независимая нефтегазовая компания: '6025'
